/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Add`; params?: Router.UnknownInputParams; } | { pathname: `/Endereco`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Registro`; params?: Router.UnknownInputParams; } | { pathname: `/../components/logo/makita`; params?: Router.UnknownInputParams; } | { pathname: `/../components/inputs/dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/Atualizar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Add`; params?: Router.UnknownOutputParams; } | { pathname: `/Endereco`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Registro`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/logo/makita`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/inputs/dropdown`; params?: Router.UnknownOutputParams; } | { pathname: `/Atualizar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Add${`?${string}` | `#${string}` | ''}` | `/Endereco${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Registro${`?${string}` | `#${string}` | ''}` | `/../components/logo/makita${`?${string}` | `#${string}` | ''}` | `/../components/inputs/dropdown${`?${string}` | `#${string}` | ''}` | `/Atualizar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Add`; params?: Router.UnknownInputParams; } | { pathname: `/Endereco`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Registro`; params?: Router.UnknownInputParams; } | { pathname: `/../components/logo/makita`; params?: Router.UnknownInputParams; } | { pathname: `/../components/inputs/dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/Atualizar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
